### ISSUE TITLE
GPU tests suggested in the documentation failing 

### ISSUE THREAD

**Issue by ViralBShah** [denizyuret/Knet.jl#568]
I'm following these instructions (on cyclops): https://denizyuret.github.io/Knet.jl/latest/install/#Installation-1

Not sure what I am doing wrong here. I should mention that cuda 10.1 is installed in `/usr/local/cuda`. The cudnn 7.6.5.32-1+cuda10.1  is installed in /usr/lib/x86_64-linux-gnu (as an unbuntu package).

```
julia> using Knet

julia> using CUDAapi; tk=find_toolkit()
1-element Array{String,1}:
 "/usr/local/cuda"

julia>  find_cuda_library("cudnn",tk)
"/usr/lib/x86_64-linux-gnu/libcudnn.so"

julia> find_cuda_library("cudart",tk)
"/usr/local/cuda/lib64/libcudart.so"

julia> include(Knet.dir("test/gpu.jl"))
Knet.gpuCount() = 9
Knet.gpu() = 6
Knet.tk = ["/usr/local/cuda"]
Knet.libknet8 = "/home/viralbshah/.julia/packages/Knet/bTNMd/deps/libknet8"
Knet.cudartfound = true
Knet.cudaRuntimeVersion = 10010
Knet.cudaDriverVersion = 10010
Knet.cudaGetDeviceCount() = 9
Knet.cudaGetDevice() = 6
Knet.cudaMemGetInfo() = (33372569600, 34058272768)
Knet.cudaDeviceSynchronize() = nothing
Knet.nvmlfound = true
Knet.nvmlDriverVersion = "418.67"
Knet.nvmlVersion = "10.418.67"
Knet.nvmlDeviceGetMemoryInfo() = (34058272768, 33372569600, 685703168)
Knet.cublashandle() = Ptr{Nothing} @0x000000000cd0b8e0
Knet.cublasVersion = 10200
gpu: Error During Test at /home/viralbshah/.julia/packages/Knet/bTNMd/test/gpu.jl:3
  Got exception outside of a @test
  UndefVarError: lib not defined
  Stacktrace:
   [1] cudnnCreate() at /home/viralbshah/.julia/packages/Knet/bTNMd/src/gpu.jl:308
   [2] cudnnhandle(::Int64) at /home/viralbshah/.julia/packages/Knet/bTNMd/src/gpu.jl:213
   [3] cudnnhandle() at /home/viralbshah/.julia/packages/Knet/bTNMd/src/gpu.jl:206
   [4] top-level scope at show.jl:613
   [5] top-level scope at /home/viralbshah/.julia/packages/Knet/bTNMd/test/gpu.jl:28
   [6] top-level scope at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113
   [7] top-level scope at /home/viralbshah/.julia/packages/Knet/bTNMd/test/gpu.jl:5
   [8] include(::String) at ./client.jl:439
   [9] top-level scope at REPL[6]:1
   [10] eval(::Module, ::Any) at ./boot.jl:331
   [11] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
   [12] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:118 [inlined]
   [13] (::REPL.var"#26#27"{REPL.REPLBackend})() at ./task.jl:358
  
Test Summary: | Error  Total
gpu           |     1      1
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/viralbshah/.julia/packages/Knet/bTNMd/test/gpu.jl:3
```

**Comment by denizyuret** [comment]
Looks like libknet8.so was never built. Can you make sure nvcc is in your
path and try Pkg.build again?

**Comment by denizyuret** [comment]
(Alternatively I can debug the problem on your machine).

**Comment by ViralBShah** [comment]
The log file is empty. 

```
viralbshah@cyclops:~$ which nvcc
/usr/local/cuda/bin/nvcc
```

**Comment by ViralBShah** [comment]
It's working now. I just wiped the slate clean and tried again.
