### ISSUE TITLE
cudnn 8.0 compatibility

### ISSUE THREAD

**Issue by kadir-gunel** [denizyuret/Knet.jl#569]
Hello, 

I can not install Knet with gpus on Fedora. I can test CUDA.jl, CUDAnative, CuArrays.jl, CUDAnative.jl without any issues, everything works fine. But with Knet I am getting `cudaDeviceGetPCIBusId: 101: invalid device ordinal` error.

The full output of testing is : 

```
┌ Warning: Knet cannot use the GPU: UndefVarError(:initialize)
└ @ Knet ~/.julia/packages/Knet/IIjk8/src/Knet.jl:165
 30.883243 seconds (28.92 M allocations: 1.863 GiB, 2.47% gc time)
Knet.gpuCount() = 2
Knet.gpu() = -1
Knet.tk = ["/usr/local/cuda-10.2"]
Knet.libknet8 = ""
Knet.cudartfound = true
Knet.cudaRuntimeVersion = 10020
Knet.cudaDriverVersion = 10020
Knet.cudaGetDeviceCount() = 2
Knet.cudaGetDevice() = 1
Knet.cudaMemGetInfo() = (8415870976, 8513978368)
Knet.cudaDeviceSynchronize() = nothing
Knet.nvmlfound = true
Knet.nvmlDriverVersion = "440.82"
Knet.nvmlVersion = "10.440.82"
gpu: Error During Test at /home/kg/.julia/packages/Knet/IIjk8/test/gpu.jl:3
  Got exception outside of a @test
  cudaDeviceGetPCIBusId: 101: invalid device ordinal
  Stacktrace:
   [1] cudaDeviceGetPCIBusId(::Int64) at /home/kg/.julia/packages/Knet/IIjk8/src/gpu.jl:33
   [2] nvmlid(::Int64) at /home/kg/.julia/packages/Knet/IIjk8/src/gpu.jl:232
   [3] nvmlDeviceGetMemoryInfo() at /home/kg/.julia/packages/Knet/IIjk8/src/gpu.jl:242
   [4] top-level scope at show.jl:613
   [5] top-level scope at /home/kg/.julia/packages/Knet/IIjk8/test/gpu.jl:22
   [6] top-level scope at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113
   [7] top-level scope at /home/kg/.julia/packages/Knet/IIjk8/test/gpu.jl:5
   [8] top-level scope at ./util.jl:175 [inlined]
   [9] top-level scope at /home/kg/.julia/packages/Knet/IIjk8/test/runtests.jl:0
   [10] top-level scope at none:6
  
Test Summary: | Error  Total
gpu           |     1      1
ERROR: LoadError: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/kg/.julia/packages/Knet/IIjk8/test/gpu.jl:3
in expression starting at /home/kg/.julia/packages/Knet/IIjk8/test/runtests.jl:4
ERROR: Package Knet errored during testing
```
So from the errors you can see that gpus actually detected but Knet cannot.
Julia version : 

```julia 
julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, haswell)
```

The default compiler is gcc version 10. But in order to make Knet work I set flags to gcc-8.2.  During the build process no issues occurred. 

Could someone please help ?

B.R.

**Comment by denizyuret** [comment]
Can you try Knet.gpu(true) and/or Knet.gpu(0), Knet.gpu(1) etc. to see if
it sees the GPU? My initial guess is that there is a mismatch between
device ids used by nvml vs cudart. Can you see which device CUDAnative
and/or CuArrays is working with? If I can understand your setup I can
update the code to prevent this from happening.

**Comment by kadir-gunel** [comment]
Hello, 

Thank you for your response. The problem is solved by rebooting. Actually, I did reboot before posting but .... magic :) 
 Now Knet sees the gpus. But this time during testing, I get  
```cudnnSetRNNDescriptor error``` many times. 

```
 2.997199 seconds (4.94 M allocations: 242.651 MiB, 1.23% gc time)
  1.158789 seconds (4.62 M allocations: 228.879 MiB, 4.17% gc time)
  6.833120 seconds (13.82 M allocations: 683.662 MiB, 2.52% gc time)
serialize: Error During Test at /home/kg/.julia/packages/Knet/bTNMd/test/serialize.jl:5
  Got exception outside of a @test
  could not load symbol "cudnnSetRNNDescriptor":
  /usr/local/cuda-10.2/lib64/libcudnn.so: undefined symbol: cudnnSetRNNDescriptor
  Stacktrace:
   [1] Knet.RD(::Int32, ::Int32, ::Knet.DD, ::Int32, ::Int32, ::Int32, ::Int32, ::Type{T} where T; handle::Ptr{Nothing}) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:257
   [2] Knet.RD(::Int32, ::Int32, ::Knet.DD, ::Int32, ::Int32, ::Int32, ::Int32, ::Type{T} where T) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:255
   [3] RNN(::Int64, ::Int64; h::Nothing, c::Nothing, handle::Ptr{Nothing}, numLayers::Int64, dropout::Float64, skipInput::Bool, bidirectional::Bool, rnnType::Symbol, dataType::Type{T} where T, algo::Int64, seed::Int64, winit::typeof(xavier_uniform), binit::typeof(zeros), finit::typeof(ones), usegpu::Bool) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:161
   [4] RNN(::Int64, ::Int64) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:147
   [5] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/serialize.jl:6
   [6] top-level scope at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113
   [7] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/serialize.jl:6
   [8] macro expansion at ./util.jl:175 [inlined]
   [9] macro expansion at /home/kg/.julia/packages/Knet/bTNMd/test/runtests.jl:10 [inlined]
   [10] macro expansion at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113 [inlined]
   [11] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/runtests.jl:6
   [12] top-level scope at none:6
  
  1.599614 seconds (4.36 M allocations: 229.830 MiB, 2.85% gc time)
JLD: Error During Test at /home/kg/.julia/packages/Knet/bTNMd/test/jld.jl:3
  Got exception outside of a @test
  could not load symbol "cudnnSetRNNDescriptor":
  /usr/local/cuda-10.2/lib64/libcudnn.so: undefined symbol: cudnnSetRNNDescriptor
  Stacktrace:
   [1] Knet.RD(::Int32, ::Int32, ::Knet.DD, ::Int32, ::Int32, ::Int32, ::Int32, ::Type{T} where T; handle::Ptr{Nothing}) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:257
   [2] Knet.RD(::Int32, ::Int32, ::Knet.DD, ::Int32, ::Int32, ::Int32, ::Int32, ::Type{T} where T) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:255
   [3] RNN(::Int64, ::Int64; h::Nothing, c::Nothing, handle::Ptr{Nothing}, numLayers::Int64, dropout::Float64, skipInput::Bool, bidirectional::Bool, rnnType::Symbol, dataType::Type{T} where T, algo::Int64, seed::Int64, winit::typeof(xavier_uniform), binit::typeof(zeros), finit::typeof(ones), usegpu::Bool) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:161
   [4] RNN(::Int64, ::Int64) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:147
   [5] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/jld.jl:7
   [6] top-level scope at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113
   [7] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/jld.jl:6
   [8] macro expansion at ./util.jl:175 [inlined]
   [9] macro expansion at /home/kg/.julia/packages/Knet/bTNMd/test/runtests.jl:11 [inlined]
   [10] macro expansion at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113 [inlined]
   [11] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/runtests.jl:6
   [12] top-level scope at none:6
  
  0.030470 seconds (5.53 k allocations: 347.281 KiB)
gcnode: Error During Test at /home/kg/.julia/packages/Knet/bTNMd/test/gcnode.jl:3
  Got exception outside of a @test
  could not load symbol "cudnnSetRNNDescriptor":
  /usr/local/cuda-10.2/lib64/libcudnn.so: undefined symbol: cudnnSetRNNDescriptor
  Stacktrace:
   [1] Knet.RD(::Int32, ::Int32, ::Knet.DD, ::Int32, ::Int32, ::Int32, ::Int32, ::Type{T} where T; handle::Ptr{Nothing}) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:257
   [2] Knet.RD(::Int32, ::Int32, ::Knet.DD, ::Int32, ::Int32, ::Int32, ::Int32, ::Type{T} where T) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:255
   [3] RNN(::Int64, ::Int64; h::Nothing, c::Nothing, handle::Ptr{Nothing}, numLayers::Int64, dropout::Float64, skipInput::Bool, bidirectional::Bool, rnnType::Symbol, dataType::Type{T} where T, algo::Int64, seed::Int64, winit::typeof(xavier_uniform), binit::typeof(zeros), finit::typeof(ones), usegpu::Bool) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:161
   [4] RNN(::Int64, ::Int64) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:147
   [5] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/gcnode.jl:8
   [6] top-level scope at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113
   [7] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/gcnode.jl:6
   [8] macro expansion at ./util.jl:175 [inlined]
   [9] macro expansion at /home/kg/.julia/packages/Knet/bTNMd/test/runtests.jl:12 [inlined]
   [10] macro expansion at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113 [inlined]
   [11] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/runtests.jl:6
   [12] top-level scope at none:6
  
  0.015141 seconds (5.21 k allocations: 324.213 KiB)
  8.586596 seconds (22.49 M allocations: 1.131 GiB, 2.69% gc time)
┌ Warning: `haskey(::TargetIterator, name::String)` is deprecated, use `Target(; name = name) !== nothing` instead.
│   caller = llvm_compat(::VersionNumber) at compatibility.jl:176
└ @ CUDAnative ~/.julia/packages/CUDAnative/e0IdN/src/compatibility.jl:176
┌ Warning: `Target(triple::String)` is deprecated, use `Target(; triple = triple)` instead.
│   caller = ip:0x0
└ @ Core :-1
 26.928755 seconds (60.99 M allocations: 3.007 GiB, 3.88% gc time)
 10.661459 seconds (26.37 M allocations: 1.303 GiB, 2.95% gc time)
 19.577044 seconds (49.89 M allocations: 2.467 GiB, 3.14% gc time)
 21.167750 seconds (53.69 M allocations: 2.688 GiB, 3.26% gc time)
 18.928654 seconds (47.22 M allocations: 2.357 GiB, 3.70% gc time)
 31.469860 seconds (72.49 M allocations: 3.585 GiB, 2.80% gc time)
 42.889722 seconds (121.28 M allocations: 5.790 GiB, 2.82% gc time)
┌ Warning: CPU convolution tests temporarily turned off.
└ @ Main ~/.julia/packages/Knet/bTNMd/test/conv.jl:31
 38.953771 seconds (101.00 M allocations: 4.900 GiB, 4.26% gc time)
rnn: Error During Test at /home/kg/.julia/packages/Knet/bTNMd/test/rnn.jl:5
  Got exception outside of a @test
  could not load symbol "cudnnSetRNNDescriptor":
  /usr/local/cuda-10.2/lib64/libcudnn.so: undefined symbol: cudnnSetRNNDescriptor
  Stacktrace:
   [1] Knet.RD(::Int32, ::Int32, ::Knet.DD, ::Int32, ::Int32, ::Int32, ::Int32, ::Type{T} where T; handle::Ptr{Nothing}) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:257
   [2] Knet.RD(::Int32, ::Int32, ::Knet.DD, ::Int32, ::Int32, ::Int32, ::Int32, ::Type{T} where T) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:255
   [3] RNN(::Int64, ::Int64; h::Nothing, c::Nothing, handle::Ptr{Nothing}, numLayers::Int64, dropout::Float64, skipInput::Bool, bidirectional::Bool, rnnType::Symbol, dataType::Type{T} where T, algo::Int64, seed::Int64, winit::typeof(xavier_uniform), binit::typeof(xavier_uniform), finit::typeof(ones), usegpu::Bool) at /home/kg/.julia/packages/Knet/bTNMd/src/rnn.jl:161
   [4] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/rnn.jl:18
   [5] top-level scope at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113
   [6] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/rnn.jl:7
   [7] macro expansion at ./util.jl:175 [inlined]
   [8] macro expansion at /home/kg/.julia/packages/Knet/bTNMd/test/runtests.jl:22 [inlined]
   [9] macro expansion at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.4/Test/src/Test.jl:1113 [inlined]
   [10] top-level scope at /home/kg/.julia/packages/Knet/bTNMd/test/runtests.jl:6
   [11] top-level scope at none:6
  
  0.344371 seconds (310.43 k allocations: 16.802 MiB)
 96.755388 seconds (217.74 M allocations: 10.453 GiB, 2.69% gc time)
108.947321 seconds (205.25 M allocations: 10.317 GiB, 2.38% gc time)
┌ Warning: optimizers is deprecated, use sgd, adam etc. instead.
└ @ Knet ~/.julia/packages/Knet/bTNMd/src/update.jl:627
151.303201 seconds (95.86 M allocations: 5.106 GiB, 1.40% gc time)
Test Summary:   | Pass  Error  Broken  Total
Knet            | 8390      4       2   8396
  gpu           |   20                    20
  distributions |    4                     4
  dropout       |    3                     3
  serialize     |           1              1
  JLD           |           1              1
  gcnode        |           1              1
  statistics    |   68                    68
  cuarray       |   99                    99
  bmm           |   39                    39
  linalg        |  200                   200
  batchnorm     |   65                    65
  loss          |  139                   139
  karray        |  328                   328
  reduction     | 1620                  1620
  conv          |   91              2     93
  rnn           |           1              1
  binary        | 3782                  3782
  unary         | 1910                  1910
  update!       |   20                    20
  optimizers    |    2                     2
ERROR: LoadError: Some tests did not pass: 8390 passed, 0 failed, 4 errored, 2 broken.
in expression starting at /home/kg/.julia/packages/Knet/bTNMd/test/runtests.jl:2
ERROR: Package Knet errored during testing
```

Do you want me to open another issue for the error ?

B.R.

**Comment by denizyuret** [comment]
Can you tell me your cudnn version? It should appear in the output of
`include(Knet.dir("test/gpu.jl"))`.

**Comment by kadir-gunel** [comment]
Knet.cudnnVersion = 8000

**Comment by kadir-gunel** [comment]
Downgrading cudnn to 7.6.5 solved it.

**Comment by denizyuret** [comment]
I have not looked at cudnn 8 yet, if there is an incompatibility I should fix it. Reopening the issue to remind myself.

**Comment by denizyuret** [comment]
Commit 28bad004 passed tests with cudnn 8.0.
