### ISSUE TITLE
Running housing.jl in Power Machine

### ISSUE THREAD

**Issue by ppalmes** [denizyuret/Knet.jl#85]
ERROR: LoadError: ccall: could not find function add_32_01 in library /home/palmesp/.julia/v0.5/Knet/src/libknet8.so

Info:
p=Cint[0]; ccall(("cudaRuntimeGetVersion","libcudart"),UInt32,(Ptr{Cint},),p); p[1]
7050

Int(ccall(("cudnnGetVersion","libcudnn"),Csize_t,()))
4007

**Comment by denizyuret** [comment]
Can you open the library file manually: Does Libdl.dlopen("
/home/palmesp/.julia/v0.5/Knet/src/libknet8.so") work?

**Comment by ppalmes** [comment]
Libdl.dlopen("./libknet8.so")
Ptr{Void} @0x0000010032e10430

**Comment by denizyuret** [comment]
Can you send the output of 'make clean; make' under Knet/src?

**Comment by ppalmes** [comment]
Thanks. That fixed it. 

I noticed that I have to remove the Knet.ji and AutoGrad.ji from time to time to make it work. Also, Pkg.build() sometimes doesn't fix the issue.

By the way, I have another power machine access with cuda-7.0. Is it possible to support this cuda version?

=======================
make clean
rm *.o *.cu libknet8.so
palmesp@ibm-power2:src$ make
julia cuda1.jl > cuda1.cu
INFO: Knet using GPU 0
nvcc -c -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "-O3 -Wall -fPIC -fopenmp" cuda1.cu -o cuda1.o
julia cuda01.jl > cuda01.cu
INFO: Knet using GPU 0
nvcc -c -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "-O3 -Wall -fPIC -fopenmp" cuda01.cu -o cuda01.o
julia cuda11.jl > cuda11.cu
INFO: Knet using GPU 0
nvcc -c -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "-O3 -Wall -fPIC -fopenmp" cuda11.cu -o cuda11.o
julia cuda12.jl > cuda12.cu
INFO: Knet using GPU 0
nvcc -c -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "-O3 -Wall -fPIC -fopenmp" cuda12.cu -o cuda12.o
julia cuda20.jl > cuda20.cu
INFO: Knet using GPU 1
nvcc -c -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "-O3 -Wall -fPIC -fopenmp" cuda20.cu -o cuda20.o
julia cuda21.jl > cuda21.cu
INFO: Knet using GPU 1
nvcc -c -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "-O3 -Wall -fPIC -fopenmp" cuda21.cu -o cuda21.o
nvcc -c -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "-O3 -Wall -fPIC -fopenmp" conv.cpp -o conv.o
nvcc --shared -O3 --use_fast_math -Wno-deprecated-gpu-targets --compiler-options "-O3 -Wall -fPIC -fopenmp" cuda1.o cuda01.o cuda11.o cuda12.o cuda20.o cuda21.o conv.o -o libknet8.so

**Comment by ppalmes** [comment]
Oh, I just checked in the other power machine that uses cuda-7.0. Knet also work now. Great and thanks!!!

**Comment by denizyuret** [comment]
Great news!  Any remaining problems?

I manually rebuilding Knet.ji in
https://github.com/denizyuret/Knet.jl/blob/master/deps/build.jl but I am
not sure why this does not solve the issue.

best,
deniz

**Comment by ppalmes** [comment]
I think only the convolution "cudnnSetConvolutionNdDescriptor_v3" still remains the problem because of the old cudnn/cuda library. is there an equivalent function for the old cuda libraries? the other machine only runs with cuda-7.0 and it will be nice if Knet supports this old cuda version.

**Comment by denizyuret** [comment]
Hm, that's strange, I worked hard on making conv.jl compatible with every
cuda/cudnn version :)  But maybe I missed something. What kind of problem
are you getting with cudnnSetConvolutionNdDescriptor_v3 ?  What are the
values of:
(Knet.cudaDriverVersion, Knet.cudaRuntimeVersion, Knet.cublasVersion,
Knet.cudnnVersion) on the problem machine?

**Comment by ppalmes** [comment]
julia> Knet.cudaDriverVersion
7000
julia> Knet.cudaRuntimeVersion
7000
julia> Knet.cudnnVersion
3000
julia> Knet.cublasVersion
7000

**Comment by ppalmes** [comment]
julia lenet.jl 
INFO: Knet using GPU 0
lenet.jl (c) Deniz Yuret, 2016. The LeNet model on the MNIST handwritten digit recognition problem from http://yann.lecun.com/exdb/mnist.
opts=(:seed,-1)(:iters,1800)(:batchsize,100)(:epochs,3)(:lr,0.1)(:atype,"KnetArray{Float32}")(:gcheck,0)(:fast,false)
INFO: Loading MNIST...
ERROR: LoadError: ccall: could not find function cudnnSetConvolutionNdDescriptor_v3 in library libcudnn
 in (::Knet.##call#158#160)(::Int64, ::Int64, ::Int64, ::Int64, ::Type{T}, ::Knet.KnetArray{Float32,4}, ::Knet.KnetArray{Float32,4}) at /localhome/paulito/.julia/v0.5/Knet/src/conv.jl:247
 in (::Core.#kw#Type)(::Array{Any,1}, ::Type{Knet.CD}, ::Knet.KnetArray{Float32,4}, ::Knet.KnetArray{Float32,4}) at ./<missing>:0
 in #conv4#81(::Ptr{Void}, ::Int64, ::Ptr{Void}, ::Int64, ::Int64, ::Array{Any,1}, ::Function, ::Knet.KnetArray{Float32,4}, ::Knet.KnetArray{Float32,4}) at /localhome/paulito/.julia/v0.5/Knet/src/conv.jl:40
 in (::Knet.#kw##conv4)(::Array{Any,1}, ::Knet.#conv4, ::Knet.KnetArray{Float32,4}, ::Knet.KnetArray{Float32,4}) at ./<missing>:0
 in predict(::Array{Any,1}, ::Knet.KnetArray{Float32,4}, ::Int64) at /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl:34
 in accuracy(::Array{Any,1}, ::Array{Any,1}, ::LeNet.#predict) at /localhome/paulito/.julia/v0.5/Knet/examples/mnist.jl:64
 in report at /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl:133 [inlined]
 in main(::Array{String,1}) at /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl:138
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl, in expression starting on

**Comment by denizyuret** [comment]
Unfortunately cudnn 3000 is not available for download any more.  The
closest I can get is:
(Knet.cudaDriverVersion,Knet.cudaRuntimeVersion,Knet.cublasVersion,Knet.cudnnVersion)
= (8000,7000,7000,3008)
and this version works without problems.

According to the official cudnn v3 docs cudnnSetConvolutionNdDescriptor had
been deprecated cudnnSetConvolutionNdDescriptor_v3 should be used.  But
maybe they introduced that somewhere between 3000 and 3008.

If you can confirm that changing L246 in Knet/src/conv.jl from:

        elseif cudnnVersion >= 3000

to

        elseif cudnnVersion > 3000

solves the problem I will make that change in the master.


deniz

**Comment by ppalmes** [comment]
i got a different error after the changes:

julia lenet.jl 
INFO: Knet using GPU 0
lenet.jl (c) Deniz Yuret, 2016. The LeNet model on the MNIST handwritten digit recognition problem from http://yann.lecun.com/exdb/mnist.
opts=(:seed,-1)(:iters,1800)(:batchsize,100)(:epochs,3)(:lr,0.1)(:atype,"KnetArray{Float32}")(:gcheck,0)(:fast,false)
INFO: Loading MNIST...
ERROR: LoadError: ccall: could not find function add_32_12 in library 
 in .+(::Knet.KnetArray{Float32,4}, ::Knet.KnetArray{Float32,4}) at /localhome/paulito/.julia/v0.5/Knet/src/broadcast.jl:64
 in predict(::Array{Any,1}, ::Knet.KnetArray{Float32,4}, ::Int64) at /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl:34
 in accuracy(::Array{Any,1}, ::Array{Any,1}, ::LeNet.#predict) at /localhome/paulito/.julia/v0.5/Knet/examples/mnist.jl:64
 in report at /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl:133 [inlined]
 in main(::Array{String,1}) at /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl:138
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl, in expression starting on line 157

**Comment by ppalmes** [comment]
i got a different error after the change:

lenet.jl 
INFO: Knet using GPU 0
lenet.jl (c) Deniz Yuret, 2016. The LeNet model on the MNIST handwritten digit recognition problem from http://yann.lecun.com/exdb/mnist.
opts=(:seed,-1)(:iters,1800)(:batchsize,100)(:epochs,3)(:lr,0.1)(:atype,"KnetArray{Float32}")(:gcheck,0)(:fast,false)
INFO: Loading MNIST...
ERROR: LoadError: ccall: could not find function add_32_12 in library 
 in .+(::Knet.KnetArray{Float32,4}, ::Knet.KnetArray{Float32,4}) at /localhome/paulito/.julia/v0.5/Knet/src/broadcast.jl:64
 in predict(::Array{Any,1}, ::Knet.KnetArray{Float32,4}, ::Int64) at /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl:34
 in accuracy(::Array{Any,1}, ::Array{Any,1}, ::LeNet.#predict) at /localhome/paulito/.julia/v0.5/Knet/examples/mnist.jl:64
 in report at /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl:133 [inlined]
 in main(::Array{String,1}) at /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl:138
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
while loading /localhome/paulito/.julia/v0.5/Knet/examples/lenet.jl, in expression starting on line 157

**Comment by denizyuret** [comment]
This is a function in libknet8.so.  Make sure this has been compiled
properly (make clean; make in Knet/src), Julia can load it
(Libdl.dlopen(Pkg.dir("Knet/src/libknet8.so")), and Knet.ji has been
regenerated (either by deleting it manually from .julia/lib/v0.5 or by
calling Pkg.build("Knet")).

**Comment by ppalmes** [comment]
same error :(

yes, i followed all the steps and repeated several times. Julia can load the libknet with dlopen. I also erased Knet.ji or Pkg.build("Knet").

**Comment by ppalmes** [comment]
it works now!!!. Pkg.build("Knet") helped. I remove Knet.ji but still the same error until I tried Pkg.build("Knet").

**Comment by ppalmes** [comment]
In summary, 

changing in conv.jl: 

        elseif cudnnVersion >= 3000
to
        elseif cudnnVersion > 3000

works for cuda-7.0 with cudnn-7.0

**Comment by denizyuret** [comment]
Awesome, I will update in master. Thanks for helping test.
